### ISSUE TITLE
trouble running test client or server

### ISSUE THREAD

**Issue by lakamsani** [AppSaloon/socket.io-tester#11]
Hi, the README instructions aren't working off the bat? The build steps worked but neither the client not the test server are running (just git cloned the repo). With node 7.5.0 on macOS Sierra.
Yarn 0.20.3 installed via homebrew.
## client empty screen. 
`node_modules/.bin/electron .`
<img width="993" alt="screen shot 2017-02-19 at 1 57 38 pm" src="https://cloud.githubusercontent.com/assets/3322496/23107155/cc25d96c-f6ac-11e6-8809-478cd8b6302e.png">

## server startup problem. 

````bash
node socketTest/index.js
/Users/vamsee/Development/git/JavaScript/socket.io-tester/socketTest/index.js:1
(function (exports, require, module, __filename, __dirname) { var app = require('express')();
                                                                                          ^

TypeError: require(...) is not a function
    at Object.<anonymous> (/Users/vamsee/Development/git/JavaScript/socket.io-tester/socketTest/index.js:1:91)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3
````

**Comment by JoJordens** [comment]
I forgot that the testserver had it's own dependencies, I moved these to the main package.json so you'll have to reinstall those and the test server will work.
I also fixed a bug that broke the client.

**Comment by lakamsani** [comment]
Did a pull, rebuilt and works with the test server. I also tried the pre-built 1.0.1 version. Thanks for making this available. 

 I would like to use to test  my own socket.io WS server that uses SSL and requires socket authentication (both features work from our own  iOS apps). This tester app isn't able to establish connection as it needs to respond to an authentication challenge for the connection to be continued by my server. If you have any pointers on what part of the tester client code to tweak I might try to get it to work with my server.

**Comment by JoJordens** [comment]
Socket connections are initiated in `src/app/js/socketManager.js` on line 68. This is probably the best spot for authentication. I've never worked with socket.io authentication myself so I'm afraid I won't be of much more help.

**Comment by morenoh149** [comment]
Same issue but perhaps for different reasons? the current master shows an empty page when following the readme. Any help appreciated.

**Comment by JoJordens** [comment]
@morenoh149 I just updated all of the dependency versions and lockfiles. Could you pull the changes, reinstall the modules and try again to see if it works now?

**Comment by morenoh149** [comment]
wow nice it loaded
