### ISSUE TITLE
Add support for messages with multiple parameters

### ISSUE THREAD

**Issue by jerrwy** [AppSaloon/socket.io-tester#12]
只能发送一个string参数或一个json参数，不支持发送多个参数吗？

**Comment by Cinezaster** [comment]
Hi @jerrwy,
Can you please describe your problem in English, I tried google translate but it doesn't make sense to me. 
Can you give an example of what you send and what you expect?

**Comment by jerrwy** [comment]
I can send message with one params now , string or json.
but how to send message with multi params

**Comment by Cinezaster** [comment]
We didn't implement this feature.
We will look into this.

**Comment by jerrwy** [comment]
ok..thanks~

**Comment by Cinezaster** [comment]
Multi parameter messages are added in version V1.1.0
