### ISSUE TITLE
Handle window resizing

### ISSUE THREAD

**Issue by ythecombinator** [AppSaloon/socket.io-tester#13]
Hey, such a great and helpful project–thank you so much!

I was wondering if a better treatment for window resizing was in your roadmap. What happens is that, when I have a large window, and want to change the event label color everything goes okay:

![captura de tela 2017-05-08 as 17 19 15](https://cloud.githubusercontent.com/assets/2644563/25823825/aa66c1f2-3413-11e7-84ef-268075313118.png)

But if I do the same on a smaller window, I simply can't see the whole color palette:

![captura de tela 2017-05-08 as 17 19 25](https://cloud.githubusercontent.com/assets/2644563/25823867/c3a57cee-3413-11e7-9b08-83cb3af95756.png)

It's not a big problem for sure, but sometimes we, as developers, don't get those small things so I just wanted to track this issue 😄

**Comment by Cinezaster** [comment]
Thank you for reporting this issue, we'll look into it.

**Comment by Cinezaster** [comment]
This also happens if you have a long list of messages on the right
