### ISSUE TITLE
Dependency update 

### ISSUE THREAD

**Issue by Cinezaster** [AppSaloon/socket.io-tester#15]
We have 3 dependencies that have newer versions.
https://www.versioneye.com/user/projects/588f5a2f5715cf0034134062?child=summary#tab-dependencies
All of them are new version and could incorporate breaking issues.
Maybe a test could be done if these new version will break things. 
No security issues force us to update these dependencies.

**Comment by JoJordens** [comment]
Updated and tested, everything still works.

**Comment by Cinezaster** [comment]
Socket.io bumped up version to V2.0.1

**Comment by Cinezaster** [comment]
Socket.io-client is bumped to V2.0.1 aswel
