### ISSUE TITLE
how to specify namespace?

### ISSUE THREAD

**Issue by nkcoder** [AppSaloon/socket.io-tester#20]
The electron version cannot specify namespace, the old version on chrome web store can.

For example, the tool can connect to **127.0.0.1:9999**, but cannot connect to **127.0.0.1:9999/socket**.
![socket-io-tester](https://user-images.githubusercontent.com/1478520/28451918-b6499992-6e22-11e7-9dc9-b23e18a62837.png)

**Comment by Cinezaster** [comment]
We discovered that indeed no socket 'connected' event is emitted when we try to connect to a namespace.
