### ISSUE TITLE
Unable to build under Windows 10

### ISSUE THREAD

**Issue by michalhainc** [AppSaloon/socket.io-tester#23]
There is somewhere a dependency on bash which makes me unable to build this under windows. 	

    PS C:\git\github\socket.io-tester> npm run build

	> _electronapp@1.1.1 build C:\git\github\socket.io-tester
	> bash .bin/build.sh

	'bash' is not recognized as an internal or external command,
	operable program or batch file.
	npm ERR! code ELIFECYCLE
	npm ERR! errno 1
	npm ERR! _electronapp@1.1.1 build: `bash .bin/build.sh`
	npm ERR! Exit status 1
	npm ERR!
	npm ERR! Failed at the _electronapp@1.1.1 build script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

	npm ERR! A complete log of this run can be found in:
	npm ERR!     C:\Users\mhainc\AppData\Roaming\npm-cache\_logs\2017-12-20T12_11_27_994Z-debug.log
	PS C:\git\github\socket.io-tester>

Output of C:\Users\mhainc\AppData\Roaming\npm-cache\_logs\2017-12-20T12_11_27_994Z-debug.log:

	0 info it worked if it ends with ok
	1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
	1 verbose cli   'C:\\Users\\mhainc\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
	1 verbose cli   'run',
	1 verbose cli   'build' ]
	2 info using npm@5.6.0
	3 info using node@v7.8.0
	4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
	5 info lifecycle _electronapp@1.1.1~prebuild: _electronapp@1.1.1
	6 info lifecycle _electronapp@1.1.1~build: _electronapp@1.1.1
	7 verbose lifecycle _electronapp@1.1.1~build: unsafe-perm in lifecycle true
	8 verbose lifecycle _electronapp@1.1.1~build: PATH: C:\Users\mhainc\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\git\github\socket.io-tester\node_modules\.bin;C:\Program Files (x86)\Eziriz\.NET Reactor;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\dotnet\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\PuTTY\;C:\Program Files\OpenVPN\bin;C:\DLang\dmd2\windows\bin;C:\Program Files\TortoiseSVN\bin;C:\Users\mhainc\Documents\Visual Studio 2015\Projects\MyUmlRest\bin;C:\Program Files (x86)\LINQPad5;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files\nodejs\;C:\Program Files (x86)\Skype\Phone\;C:\Users\mhainc\AppData\Roaming\npm;c:\Program Files\Java\jdk1.8.0_131\\lib;C:\Program Files\TortoiseGit\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\WinMerge;C:\Program Files (x86)\Xoreax\IncrediBuild;C:\Users\mhainc\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\mhainc\AppData\Local\Programs\Python\Python36\;C:\Users\mhainc\AppData\Local\Microsoft\WindowsApps;C:\Users\mhainc\AppData\Roaming\npm;C:\Program Files (x86)\Nmap;C:\Users\mhainc\AppData\Roaming\npm\;C:\Users\mhainc\AppData\Local\GitHubDesktop\bin;C:\Program Files\Microsoft VS Code\bin;C:\Users\mhainc\AppData\Local\Programs\Fiddler;C:\Users\mhainc\AppData\Local\Microsoft\WindowsApps
	9 verbose lifecycle _electronapp@1.1.1~build: CWD: C:\git\github\socket.io-tester
	10 silly lifecycle _electronapp@1.1.1~build: Args: [ '/d /s /c', 'bash .bin/build.sh' ]
	11 silly lifecycle _electronapp@1.1.1~build: Returned: code: 1  signal: null
	12 info lifecycle _electronapp@1.1.1~build: Failed to exec build script
	13 verbose stack Error: _electronapp@1.1.1 build: `bash .bin/build.sh`
	13 verbose stack Exit status 1
	13 verbose stack     at EventEmitter.<anonymous> (C:\Users\mhainc\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
	13 verbose stack     at emitTwo (events.js:106:13)
	13 verbose stack     at EventEmitter.emit (events.js:194:7)
	13 verbose stack     at ChildProcess.<anonymous> (C:\Users\mhainc\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
	13 verbose stack     at emitTwo (events.js:106:13)
	13 verbose stack     at ChildProcess.emit (events.js:194:7)
	13 verbose stack     at maybeClose (internal/child_process.js:899:16)
	13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
	14 verbose pkgid _electronapp@1.1.1
	15 verbose cwd C:\git\github\socket.io-tester
	16 verbose Windows_NT 10.0.16299
	17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mhainc\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
	18 verbose node v7.8.0
	19 verbose npm  v5.6.0
	20 error code ELIFECYCLE
	21 error errno 1
	22 error _electronapp@1.1.1 build: `bash .bin/build.sh`
	22 error Exit status 1
	23 error Failed at the _electronapp@1.1.1 build script.
	23 error This is probably not a problem with npm. There is likely additional logging output above.
	24 verbose exit [ 1, true ]

**Comment by BorntraegerMarc** [comment]
A download for windows also would be

**Comment by Cinezaster** [comment]
@BorntraegerMarc https://github.com/AppSaloon/socket.io-tester/releases We have releases for windows.
Let me know if something is wrong with it?

**Comment by BorntraegerMarc** [comment]
Ah thanks @Cinezaster ! I just looked at http://appsaloon.github.io/socket.io-tester/ and didn't see a windows download link :)

**Comment by Cinezaster** [comment]
The page is indeed not up to date. Will fix this #28
