### ISSUE TITLE
1.2.1 release download actually contains 1.2.0 code

### ISSUE THREAD

**Issue by aramando** [AppSaloon/socket.io-tester#27]
At least for the Darwin x64 build: https://github.com/AppSaloon/socket.io-tester/releases/download/v1.2.1/socket-io-tester-darwin-x64.zip

**Comment by Cinezaster** [comment]
This should be correct, because of a security vulnerability in electron we had to update the version of the electron package. 
Nothing changed except the version of Electron

**Comment by aramando** [comment]
OK, but I don't see why that should stop you from incrementing the app version? The problem is that the latest version is reporting to users that it is not the latest version.

**Comment by JoJordens** [comment]
Even though we updated the electron version and made a new release, the version in the app itself wasn't incremented. But it should have. I'll make a new release to make sure everyone gets the correct version.

**Comment by aramando** [comment]
Great, thanks. Sorry, I could have been more specific in my initial description :)

**Comment by JoJordens** [comment]
Thank you for pointing out the version was wrong. :) The new release is available now.
