### ISSUE TITLE
query parameters can't be obtained with socker.io server

### ISSUE THREAD

**Issue by yokotak0527** [AppSaloon/socket.io-tester#37]
I'm using Electron. I wrote script of main process as follows.

```js
// main process as the server
let io = require('socket.io')(2000); // listen to http://localhost:2000

io.on('connect', scoket => {
    console.log(socket.handshake.query);
});
```

When I access http: // localhost: 2000?name=hoge with socket.io tester, socket.io server output `{ EIO: '3', transport: 'polling', t: 'MQ0oF8j' }` to console, and can't retrieve `name` query.

but, when I use socket.io-client instead of socket.io tester I can get `name` quiery.

```js
const io = require('socket.io-client');
let socket = io('http://localhost:2000?name=hoge');
```

socket.io server output `{ name: 'hoge', EIO: '3', transport: 'polling', t: 'MQ0uBj_' }` to console.

**Comment by Cinezaster** [comment]
@yokotak0527 We parse the url in socket.io tester and we never implemented query parameters. 
We'll implement this in the next version

**Comment by Nishchit14** [comment]
[Firecamp](https://chrome.google.com/webstore/detail/firecamp/eajaahbjpnhghjcdaclbkeamlkepinbl) would solve your problem @yokotak0527 

![image](https://user-images.githubusercontent.com/5078921/50572939-3e4c2300-0df0-11e9-8ce8-ac88a5d732fe.png)
