### ISSUE TITLE
Set up events to listen on before connecting

### ISSUE THREAD

**Issue by NobbZ** [AppSaloon/socket.io-tester#38]
I want to set up the events to listen on prior to connecting for at least these 2 reasons:

1. During development I shutdown and restart the server multiple times and I have to set up the events I want to look at after each restart, this costs valuable time
2. When connecting the server emits a `"welcome"` event as a "reply" to my connection, I'd like be able to see it.

**Comment by Nishchit14** [comment]
[Firecamp](https://chrome.google.com/webstore/detail/firecamp/eajaahbjpnhghjcdaclbkeamlkepinbl) would solve your problem,  @NobbZ 

![image](https://user-images.githubusercontent.com/5078921/50572929-e9a8a800-0def-11e9-9e0c-7cd987f014c7.png)
