### ISSUE TITLE
Wrong download links

### ISSUE THREAD

**Issue by postpersonality** [AppSaloon/socket.io-tester#39]
![screenshot from 2018-10-30 17-51-43](https://user-images.githubusercontent.com/2012215/47726916-7e661c80-dc6c-11e8-9af4-1b0360d9b20a.png)
All the buttons lead to the same `socket-io-tester-linux-armv7l.zip` file. 
* OS: Debian 9
* Browser: Chrome 69.0.3497.100 (Official Build) (64-bit)

**Comment by JoJordens** [comment]
It's been resolved. Each button now links to the correct file.
