### ISSUE TITLE
option to save events and parameters

### ISSUE THREAD

**Issue by startgeek** [AppSaloon/socket.io-tester#41]
I believe that re-config for each time that I disconnected from server and connect again is super painful if there was an option to save events and params it would be awesome this app could become a big app like postman 
thanks in advance

**Comment by Nishchit14** [comment]
Firecamp would solve your exact problem, you can download from [Firecamp app](https://chrome.google.com/webstore/detail/firecamp/eajaahbjpnhghjcdaclbkeamlkepinbl).



![image](https://user-images.githubusercontent.com/5078921/50572854-24f6a700-0def-11e9-8482-d5967b277f69.png)

**Comment by startgeek** [comment]
wow thanks a lot
