### ISSUE TITLE
Unable to view full connection log

### ISSUE THREAD

**Issue by Dragas** [AppSaloon/socket.io-tester#42]
Often it is unclear what is going on and why something is not working when you fail to connect to your socket io server. How do I view the full connection log: exception that occur during connection, reasons for connection being dropped, etc.?

**Comment by Cinezaster** [comment]
[Try firecamp](https://chrome.google.com/webstore/detail/firecamp-a-campsite-for-d/eajaahbjpnhghjcdaclbkeamlkepinbl)
