### ISSUE TITLE
Can't connect to my node.js

### ISSUE THREAD

**Issue by fibin** [AppSaloon/socket.io-tester#43]
I have downloaded test app and run it throw cmd. socket.it-tester can see and easily connect to 127.0.0.1:3150. But when I start my other app that works on 127.0.0.1:400 I can't connect to it. But the app works fine. What's wrong? What changes in my app I need to do to make it visible for socket.io-tester

**Comment by GBRGit** [comment]
@fibin you can test with Firecamp [chrome.google.com/webstore/detail/eajaahbjpnhghjcdaclbkeamlkepinbl](url) to check out your SocketIO code.
