### ISSUE TITLE
Passing data on connection event

### ISSUE THREAD

**Issue by igoras1993** [AppSaloon/socket.io-tester#54]
There should be an option to pass data while connection event. In such case, client passes data in request payload, e.g.:

`var c = io.connect('http://1.1.1.1:8080/', { query: "foo=bar" })`

Is that option present in Your software? I've tried adding a payload into request url (`.../socket.io/?foo=bar`) but it does not work. If not - I am highly suggesting adding it :) Without - it is actually useless for testing in apps with client authorization.

**Comment by Cinezaster** [comment]
Hi @igoras1993 .
This project is unmaintained at the moment because of other en beter solutions
try [firecamp](https://chrome.google.com/webstore/detail/firecamp-a-campsite-for-d/eajaahbjpnhghjcdaclbkeamlkepinbl)
